parameters:
    models: CE-VAE
    epoch: [600]
    beta: [0.001]
    lambda_l2: [0.001]
    lambda_keyphrase: [1.0]
    lambda_latent: [1.0]
    lambda_rating: [1.0]
    rank: [200]
    corruption: [0.4]
    optimizer: [Adam]
    learning_rate: [0.0005]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall, MAP]
